### ISSUE TITLE
Adjustments to app icon to match Microsoft’s

### ISSUE THREAD

**Issue by BreeceW** [jenius-apps/ambie#104]
Ambie’s icon is rather smaller than other circular icons. Additionally, the shadow is used in the taskbar and the app list, whereas the inbox apps only have shadows on the tiles.

App list:
![image](https://user-images.githubusercontent.com/18747724/104496555-2266e480-55a7-11eb-8b4c-fe52d3ad2213.png)
Taskbar:
![image](https://user-images.githubusercontent.com/18747724/104496565-2430a800-55a7-11eb-9215-d97beb8a256c.png)
Tiles:
![image](https://user-images.githubusercontent.com/18747724/104496987-b46eed00-55a7-11eb-8ee4-b94fd5aa1e7a.png)

**Comment by dpaulino** [comment]
Fixes coming in the next update. Thanks!
