### ISSUE TITLE
Feature request: Add progress circle beside sounds when downloading from Sound Catalogue

### ISSUE THREAD

**Issue by Cyberdroid1** [jenius-apps/ambie#105]
As of now, when downloading sounds, a loading circle appears which does not tell progress. I feel if it is replaced with one that shows progress, it would be great and also gives a sense of satisfaction, and that it is not stuck, since the download size of all sounds is different.

**Comment by dpaulino** [comment]
note to self: try using this https://github.com/bloomtom/HttpProgress
