### ISSUE TITLE
[Feature] Reorganise sounds

### ISSUE THREAD

**Issue by KristofKekesi** [jenius-apps/ambie#111]
Ability to drag and drop sounds to reorganise them.

**Comment by dpaulino** [comment]
note to self: use 
```
CanReorderItems="True" AllowDrop="True"
```

**Comment by michael-hawker** [comment]
Since the catalog is growing too, it could be handy to have a 'favorite' feature where you can star your favorite sounds and have them in a separate bucket at the top?

Maybe a 'most recently' listened bucket too?

Make it feel like Netflix 😋

**Comment by Jude24to25** [comment]
Yes, this would be excellent!

**Comment by onethirdzero** [comment]
> Since the catalog is growing too, it could be handy to have a 'favorite' feature where you can star your favorite sounds and have them in a separate bucket at the top?

I started a separate issue for that in case anybody else wants to drop ideas/related requests there: #245

**Comment by shef3r** [comment]
already fixed a long time ago in #304
