### ISSUE TITLE
[Question] Redeem Code button?

### ISSUE THREAD

**Issue by michael-hawker** [jenius-apps/ambie#116]
It took me a bit to realize I had to go to the store and redeem the code there. Is there an app-based workflow that you can initiate for the user to help them?

(Maybe this isn't a common scenario, but it was making me think in general how an app developer would do this.)

**Comment by dpaulino** [comment]
cool idea! I think it may be possible by opening up a webview. Not sure if there's an API available though

**Comment by dpaulino** [comment]
After some thought, I'm going to close this issue for now. The redeemable code that I gave out in the past will be a rare event, and so I don't think I'll add anything in the app for this scenario for now. I'll just make sure that if codes are given out in the future, I'll specify the URL where you can redeem the code.
