### ISSUE TITLE
Sound Tiles Zoom Issue on Tap and Scroll

### ISSUE THREAD

**Issue by EzraWard** [jenius-apps/ambie#120]
To reproduce:
1. Open Ambie on a touchscreen PC.
2. Tap any sound tile and begin to scroll the screen without lifting finger.
3. Note that the sound tile "zooms" but does not return to normal size when the finger is lifted.

Discovered on Dell Venue 8 Pro, reproduced on a Surface Book 3.

Video link of bug in action: https://youtu.be/tqr7VkUZmnQ

**Comment by dpaulino** [comment]
Thanks, I'll address this soon!

**Comment by dpaulino** [comment]
@EzraWard fix is coming in the next update. Thank you for the feedback!

**Comment by dpaulino** [comment]
now available in the v1.2.2 update. Let me know if you're still having issues

**Comment by EzraWard** [comment]
Thank you for fixing this and for building Ambie!
