### ISSUE TITLE
Not clear when Sound Mix is selected.

### ISSUE THREAD

**Issue by michael-hawker** [jenius-apps/ambie#127]
I noticed when I resumed the app after being offline for the weekend, that there were three different sounds selected:

![image](https://user-images.githubusercontent.com/24302614/107334983-40234e80-6a6c-11eb-929e-42f565422620.png)

I wasn't sure at first if this was my existing mix or not:

![image](https://user-images.githubusercontent.com/24302614/107335016-4adde380-6a6c-11eb-9ef3-c5ca6e0741ea.png)

Which it is, as I can click on the mix to stop/start the sound.

Request: It'd be nice for the mix box itself to also have a speaker to represent this mix itself is playing vs. the individual sounds?

Maybe this ties into #111 as well if there's different categories of the loose sounds vs. mixes?

**Comment by dpaulino** [comment]
Fixed in 1.5.1
