### ISSUE TITLE
Add Elevator Music

### ISSUE THREAD

**Issue by michael-hawker** [jenius-apps/ambie#128]
Did a bit of poking and stumbled upon this agreeable license one: https://orangefreesounds.com/elevator-music/

But was hoping of also something a little bit more mellow like the one from https://exclusive.website/

Maybe there's a few options depending on what else we can find?

(Also, should there be issue templates in the repo to help auto-label things like sounds requests vs. bugs vs. features?)

**Comment by michael-hawker** [comment]
Ah, Kimbra pointed out that I didn't scroll to the bottom of the page where the music credit was, it's available here: https://www.bensound.com/royalty-free-music/track/the-elevator-bossa-nova

I like both though now! 😋

**Comment by dpaulino** [comment]
now available

**Comment by dpaulino** [comment]
![image](https://user-images.githubusercontent.com/7649589/107393093-3969fb00-6aaf-11eb-921e-f2de9e4d3e60.png)
