### ISSUE TITLE
Android app?

### ISSUE THREAD

**Issue by mizzunet** [jenius-apps/ambie#152]
Not sure if it's right place to ask, but I wonder any chance for Amble android app? I really would like use it on my android phone as well. Thank you

**Comment by dpaulino** [comment]
Hello, thanks for the issue. Android support has been discussed here: https://github.com/jenius-apps/ambie/issues/21. Closing this ticket as duplicate.

**Comment by mizzunet** [comment]
> Hello, thanks for the issue. Android support has been discussed here: #21. Closing this ticket as duplicate.

Oops, sorry
