### ISSUE TITLE
Crash when changing OS accent colour

### ISSUE THREAD

**Issue by dpaulino** [jenius-apps/ambie#153]

**Comment by Crimson-Blade** [comment]
I was about to open an issue for this lmao. In my case it crashed when I opened settings, once again when i tried to share the app, and just now as i'm writing this XD. The app seems to be VERY unstable

**Comment by dpaulino** [comment]
> I was about to open an issue for this lmao. In my case it crashed when I opened settings, once again when i tried to share the app, and just now as i'm writing this XD. The app seems to be VERY unstable

Can you record a video showing the crash for settings? It would really help me

**Comment by dpaulino** [comment]
Did some digging. The crash itself is not caught by the debugger in VS2019. It appears the crash is caused by something from WinUI. Here's some info in the Windows Event Viewer. 

![image](https://user-images.githubusercontent.com/7649589/114342050-f27c9e00-9b0f-11eb-8c3a-d89346abf454.png)


I may need to open a bug in https://github.com/Microsoft/microsoft-ui-xaml

**Comment by dpaulino** [comment]
More digging. It seems the crash does not occur if I remove the WinUI Teaching Tip control. When I add it back, the crash occurs again.

**Comment by Jude24to25** [comment]
For me, the app crashes at least once per hour. It seems that it crashes ON the hour (e.g. 1:00, 2:00, 3:00, etc.). However, sometimes it will also crash before then. One time it was crashing whenever I would select "Next desktop background", but I cannot always replicate that crash.

**Comment by AnalogFeelings** [comment]
Can't replicate anymore, even with the accent color changes from yesterday. May be fixed upstream?
