### ISSUE TITLE
Feature Request: Icon selection

### ISSUE THREAD

**Issue by chonty** [jenius-apps/ambie#167]
Would it be possible to add another icon in a different colour and make it selectable in the options?  I keep seeing the orange colour on my taskbar and mistaking it for a Teams message.

**Comment by dpaulino** [comment]
Do you mean replace the orange Ambie icon? I don't think this is doable unfortunately. But even if it were, I don't want to change the logo since it's part of Ambie's brand.

**Comment by chonty** [comment]
That's fair.  I'm getting used to it now!
