### ISSUE TITLE
Title of current profile in flyout

### ISSUE THREAD

**Issue by luximus-hunter** [jenius-apps/ambie#171]
Hiya,

I use [ModernFlyouts](https://github.com/ModernFlyouts-Community/ModernFlyouts), and I see that there is no information about the current tracks playing.

![LXMS1621346364](https://user-images.githubusercontent.com/49814847/118667653-7a7f5300-b7f4-11eb-8a0b-080aa3cfa0de.png)

Is it an option to support this? As well as to display the name of the tracks that are playing? Similar to Spotify.

![LXMS1621347211](https://user-images.githubusercontent.com/49814847/118667927-b1556900-b7f4-11eb-8cf5-19881a310daf.png)
![LXMS1621347074](https://user-images.githubusercontent.com/49814847/118667944-b4505980-b7f4-11eb-8978-88c795e82ff5.png)

**Comment by dpaulino** [comment]
I can probably add support for the title, but the image will likely have to stay the generic Ambie image. Thanks for the feedback!

**Comment by luximus-hunter** [comment]
Of course!

**Comment by janwiebedroid** [comment]
Made a PR here: https://github.com/jenius-apps/ambie/pull/288
