### ISSUE TITLE
Crash when stwitching from Catalogue to Home

### ISSUE THREAD

**Issue by AndRo-Marian** [jenius-apps/ambie#189]
Faulting application name: AmbientSounds.Uwp.exe, version: 1.0.0.0, time stamp: 0x60d5678c
Faulting module name: Windows.UI.Xaml.dll, version: 10.0.17763.1852, time stamp: 0x65d1ccdd
Exception code: 0xc000027b
Fault offset: 0x0000000000701c82
Faulting process id: 0x21f0
Faulting application start time: 0x01d76ae9bbfa0b9b
Faulting application path: C:\Program Files\WindowsApps\43891JeniusApps.Ambie_2.0.4.0_x64__jaj7tphbgjeh8\AmbientSounds.Uwp.exe
Faulting module path: C:\Windows\System32\Windows.UI.Xaml.dll
Report Id: b3e2ff3f-2748-4786-b444-a20fd9f278c3
Faulting package full name: 43891JeniusApps.Ambie_2.0.4.0_x64__jaj7tphbgjeh8
Faulting package-relative application ID: App

**Comment by dpaulino** [comment]
@AndRo-Marian what steps do you take that causes this crash? Launch app > navigate to cataloge > wait 5 secs > go back to home?

**Comment by dpaulino** [comment]
And what's your OS version?

**Comment by AndRo-Marian** [comment]
version: 10.0.17763.1852
Launch - Catalogue - Home
Time doesn't matter.

**Comment by dpaulino** [comment]
@AndRo-Marian thank you for the info. It seems that the crash is only happening on older versions of windows. I'll investigate further.

**Comment by dpaulino** [comment]
@AndRo-Marian what happens when you reinstall the app? does it still crash when you do Reinstall > launch > catalogue > back to home?

**Comment by AndRo-Marian** [comment]
![OOjuY2D0Ps](https://user-images.githubusercontent.com/48178307/123531474-9cca9180-d70d-11eb-9dd7-c87e6560c334.gif)

**Comment by dpaulino** [comment]
@AndRo-Marian thanks for your gif! I think it's an issue with the animation of the Home and Catalogue buttons. I can't seem to reproduce it yet though. I see from your gif that you seem to have disabled some OS animations or something. Any chance you can share your configuration? I'm curious if that's related to the issue

**Comment by AndRo-Marian** [comment]
Try disable "Show animations on Windows"

**Comment by dpaulino** [comment]
That's it! I reproduced the crash by disabling all OS animations!
![image](https://user-images.githubusercontent.com/7649589/123531935-6b29da00-d6bd-11eb-8fa7-45e202a617a7.png)

**Comment by dpaulino** [comment]
I fixed the bug :) Coming asap to the next update! ETA Monday since that's Microsoft Store doesn't review app submissions on the weekend

**Comment by AndRo-Marian** [comment]
First one is, or the 
![image](https://user-images.githubusercontent.com/48178307/123532016-064c9f00-d712-11eb-9421-79adedeba7d1.png)
From Display settings.But seams the animations is causing it.

**Comment by AndRo-Marian** [comment]
Nice and Thanks.

**Comment by dpaulino** [comment]
Summary

Issue
- Crash occurs for some users when they navigate from Catalogue to Home

Root Cause
- This occurs for only users who turned off OS animations
- The code was attempting to perform a connected animation from the Catalogue page too late in the navigation process
- The UI element to animate had already been removed from the visual tree, causing the crash

Fix
- Setup the connection animation earlier in the navigation process (in fact, before the navigation is triggered)
- Commit of the fix: https://github.com/jenius-apps/ambie/commit/dee76e23c054fe3ee4d0f77f0d1674b7873f38cc
