### ISSUE TITLE
Clicking on a sound that's playing should stop it

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [jenius-apps/ambie#195]
I keep trying to click on the playing sound to remove it from the current playing list but that doesn't work and I need to remove it using the X button. Please make it so if you click on an already playing sound, it will stop playing it.

**Comment by dpaulino** [comment]
I was just about to add this back 😛 thanks for the feedback

**Comment by dpaulino** [comment]
Fixed by https://github.com/jenius-apps/ambie/commit/7d4a4d9bd70c824497684fd3dc15138e1e750ed8
