### ISSUE TITLE
The sounds don't loop

### ISSUE THREAD

**Issue by bzzrak** [jenius-apps/ambie#217]
Seemingly every sound in the app doesn't loop. They all end at some point, leaving a couple of seconds of silence, and then they start again. That really brings me out of vibe, so to say, and prevents me from enjoying the app fully. 

I would really appreciate it if the sounds were made to loop, at least the simpler ones like White Noise.

**Comment by dpaulino** [comment]
there's some technical challenges in solving this issue, particularly a storage problem. I'm working through them now, but it will take some time. appreciate your patience, and thanks for creating an issue.

**Comment by dpaulino** [comment]
Note: the PR above only fixes the issue for the "white noise" sound. Other sounds still have issues. If this fix is successfully received, I'll apply it to the other sounds as well

**Comment by dpaulino** [comment]
Ambie 2.0.17 is now available with the fix

**Comment by bzzrak** [comment]
Much better thank you
