### ISSUE TITLE
Feature Request: Compact-Overlay Support

### ISSUE THREAD

**Issue by Saijin-Naib** [jenius-apps/ambie#22]
I'd love to see Compact Overlay Support as an option for Desktop clients

**Comment by dpaulino** [comment]
note to self: docs on compact overlay https://programmer.group/uwp-use-compact-overlay-mode-to-always-display-on-the-front-end.html

**Comment by dpaulino** [comment]
coming soon 
![image](https://user-images.githubusercontent.com/7649589/98645170-7115ab00-22e6-11eb-8cd9-489daf1d2b0b.png)
