### ISSUE TITLE
Edit and delete saved mixes

### ISSUE THREAD

**Issue by shmu26** [jenius-apps/ambie#235]
If I click the save button on a mix,  it gets added to the list of sounds. How can I edit the name of the saved mix, or delete the mix from the list?
If this is not currently supported, I suggest it as a feature. 
Great app!

**Comment by dpaulino** [comment]
Currently can't edit the mix, but you can delete it by right clicking on the mix and clicking delete. Does this work for you @shmu26 ?

**Comment by shmu26** [comment]
I do not get any options with a right click

**Comment by dpaulino** [comment]
Interesting. You don't see this pop up with a right-click?
<img width="205" alt="image" src="https://user-images.githubusercontent.com/7649589/165226758-23b108c1-2f49-4c9b-82e9-94880d14fd2c.png">


Can you send me a video recording of what your screen looks like as you attempt to right click on a mix?

**Comment by shmu26** [comment]
Solved.
I had resized the app window to make it thin, so thin that it hid the image
associated with each sound. That also hid the right-click menu. After I
broadened out the app window, it functions as expected.
