### ISSUE TITLE
Enhancement: Auto hide buttons in full screen mode

### ISSUE THREAD

**Issue by yaichenbaum** [jenius-apps/ambie#236]
**Problem**
The full screen mode is a great way to hide distractions but there are a couple UI elements that are still visible.

**Proposal**
Auto hiding the buttons after a couple of seconds without user any interactions would help solve this issue. It's important that all interaction modes are accounted for including touch so that touching the display makes the buttons visible again.

**Comment by hunterlan** [comment]
I discovered this page ([link](https://docs.microsoft.com/en-us/windows/apps/design/input/mouse-interactions)) which responsible for user interactions. After the main work I'll try to implement it.
