### ISSUE TITLE
Theme switcher doesn’t update if user navigated to screen saver page first

### ISSUE THREAD

**Issue by BreeceW** [jenius-apps/ambie#243]
Click the Screensaver mode button, then go back. Open Theme settings. Try changing the background to one of the images. It should update the background after you click it, but it does not. On restarting, the background will be the right image.
This is Ambie V3 running on Windows 11 x64 stable.

**Comment by BreeceW** [comment]
This is because ShellPageViewModel is unsubscribing from the settings updated event when the Dispose method is called (by the way this is confusing since it does not implement IDisposable) right here https://github.com/jenius-apps/ambie/blob/main/src/AmbientSounds/ViewModels/ShellPageViewModel.cs#L117, but it is never re-subscribed to when the ShellPage is navigated back to.

**Comment by dpaulino** [comment]
Great find! Do you want to take a stab at fixing it? No worries if not, I can fix it tonight

**Comment by dpaulino** [comment]
nvm, just fixed it! Fixed in https://github.com/jenius-apps/ambie/commit/8924d5c5e83c0acd6cd4da566b75b4f95690139d
