### ISSUE TITLE
Settings menu on screen saver page is empty

### ISSUE THREAD

**Issue by itsWindows11** [jenius-apps/ambie#247]
Steps to reproduce:
1. Disable the "Use dark page as screen saver" option if its enabled, and restart the app
2. Go to screensaver mode, then go back
3. Enable the "Use dark page as screen saver" option
4. Go to screensaver mode again
5. Click on the settings button at top right

There should be an empty menu and the screensaver stays as is without changes.

Screenshots:

Without enabling the option:
![image](https://user-images.githubusercontent.com/81253203/172462725-df379a87-ad45-4d8d-a75d-16e52edcf140.png)

With enabling the option:
![image](https://user-images.githubusercontent.com/81253203/172462917-d844a2d3-83b0-4217-a909-1ba40497087c.png)

**Comment by dpaulino** [comment]
Nice find, thanks!

**Comment by dpaulino** [comment]
Fixed here https://github.com/jenius-apps/ambie/commit/82f876a3b307fa94109f1aef19ecc1ec8d04c860
