### ISSUE TITLE
Acrylic theme

### ISSUE THREAD

**Issue by Pinox** [jenius-apps/ambie#248]
Hi Guys,

Awesome app firstly,  luv using this app.  

A nice added touch will be to include and Acrylic theme in your theme settings where it displays the current pc desktop background.  With Bing wallpaper rotating images on the desktop that will create nice added effect.

![image](https://user-images.githubusercontent.com/5297255/172564584-9783cd49-60c5-4258-a2e7-3c89b6835752.png)

![image](https://user-images.githubusercontent.com/5297255/172564662-41b93a23-3023-41d7-8835-bdb2cf5313a1.png)

**Comment by dpaulino** [comment]
Hi @Pinox thanks for using Ambie! Unfortunately, [Microsoft updated their guidelines to say that acrylic is only recommended for short-lived, transient surfaces like flyouts](https://docs.microsoft.com/en-us/windows/apps/design/style/acrylic#when-to-use-acrylic). This means that acrylic is no longer recommended for the background of an app. Thus, I will keep the current design as is for now unless more and more people want to try seeing acrylic. Also note that on Windows 11, the app's background is using Mica which is the new recommended design.

Sorry if I'm being a downer, but just wanted to be honest and set expectations.

**Comment by Pinox** [comment]
Thanks for reply @dpaulino. It's not a downer, it's just your app is a great showcase for how a beautiful app should look like ;))
I thought Mica & Background Acrylic will be an good addition as it's now available in the Windows App SDK 1.1.0 but I forgot this is a UWP app and not a WinUI 3 app. Just out of interest are you planning to upgrade it to WinUI 3 in the future or does the benefits of UWP (.net native) still outweight WinUI3 ?

**Comment by dpaulino** [comment]
Right yeah, Ambie is a c# xaml uwp app. I am not planning to update Ambie to WinUI 3 because Ambie must run on Xbox and uwp's performance/memory usage is still better than WinUI 3 (at least last I checked).
