### ISSUE TITLE
[A11y] Slider HelpText not being announced

### ISSUE THREAD

**Issue by dpaulino** [jenius-apps/ambie#252]
These sliders have a HelpText in the code, but narrator is not announcing it. You can see from Accessibility Insights that the helpText exists, though.
<img width="605" alt="image" src="https://user-images.githubusercontent.com/7649589/172984484-38fd10f7-1091-4c25-bc8e-c664b608cfb8.png">

<img width="326" alt="image" src="https://user-images.githubusercontent.com/7649589/172984391-ba471153-4b9a-42be-a31a-4240ecb52184.png">

**Comment by AnalogFeelings** [comment]
Tested in Windows 11 build 26080, and it doesnt seem to be the case anymore. It can read the help text properly.
