### ISSUE TITLE
Sound effects downloaded from the category cannot be played

### ISSUE THREAD

**Issue by TimmonSha** [jenius-apps/ambie#260]
I tried download new sound from the category. However, the downloaded sound effects do not play. No sound after mouse click on the new sound effect, but the original sound effect can be played.

There is no sound when you click on a new sound effect (elevator music).
![image](https://user-images.githubusercontent.com/21191077/175282153-8cd838c6-ca41-4bd6-9849-2d3c5f8dd9e1.png)

Click on the original sound effect which can be played.
![image](https://user-images.githubusercontent.com/21191077/175282463-6ff10fe7-9d81-4f8f-b054-ee3dba7e1744.png)

version: 3.0.13.0, downloaded from Microsoft Store.

**Comment by dpaulino** [comment]
Can you try deleting it and then downloading again? Or does this always happen?

**Comment by TimmonSha** [comment]
First of all, thank you for the great app. 
I think I may know the reason, it may have something related to the installation locations.
When I install the software on a non-C drive (like the D drive) and download the new sound effects, the sound effects can not play normally.
When I install the software on the C drive and download the new sound effects, the sound effects can play normally.

**Comment by dpaulino** [comment]
Interesting. How did you download the app to a non-C drive? I will try to replicate the issue

**Comment by TimmonSha** [comment]
Oh, I just download the app from the Microsoft Store, and then move the location of this application to the D drive in the settings . (Settings->Apps->Apps & Features->find Ambie->3 dots->move).

**Comment by dpaulino** [comment]
Closing ticket since it's specific to moving the installation path, which is currently an edge case. If this issue occurs for more people, I'll reopen
