### ISSUE TITLE
Changing window size cuts off the large text in Focus Timer

### ISSUE THREAD

**Issue by maciej-klupp** [jenius-apps/ambie#273]
On the focus timer screen the center text below the timer gets cut off after changing the window size:

![scaling](https://user-images.githubusercontent.com/100523238/182042643-1fa2a31c-3f4e-4e86-ac2d-a46bc83e199f.gif)

**Comment by dpaulino** [comment]
Fixed https://github.com/jenius-apps/ambie/commit/f6acea9a767df1c65138f007516c848201791c69
<img width="675" alt="image" src="https://user-images.githubusercontent.com/7649589/183013314-9df8829d-4933-453b-8a9b-2552b58acb16.png">
