### ISSUE TITLE
Taskbar Playback buttons issue

### ISSUE THREAD

**Issue by miyassin** [jenius-apps/ambie#290]
The taskbar playback buttons don't look right in dark mode. Windows 11 22H2. I attached two screenshots of Ambie and Spotify for comparison.
![Screenshot 2022-10-10 113106](https://user-images.githubusercontent.com/33951993/195005547-36982d5e-7309-47fa-bcea-bc151dce955a.png)
![Screenshot 2022-10-10 113140](https://user-images.githubusercontent.com/33951993/195005568-11135cae-f305-4f32-9e8a-4970756b3989.png)

**Comment by dpaulino** [comment]
These buttons are completely handled by Windows for UWP apps like Ambie. I think spotify is capable of editing it because spotify is a win32 app, but for apps like Ambie, there's absolutely zero control over these buttons. I recommend sending this as feedback to Feedback Hub under Taskbar.
