### ISSUE TITLE
[Bug] no app name/icon in the media player/overlay (insider build 25276)

### ISSUE THREAD

**Issue by shef3r** [jenius-apps/ambie#323]
![There's no app name or the little icon in the corner.](https://user-images.githubusercontent.com/79228174/214622085-e6e34c8a-261b-4b20-a5b7-7822a61d85fd.png)
Shouldn't there be some kind of icon in the corner like usual? And the name should definitely be "Ambie".
I'm not sure if this is an issue of the insider build or the app, but i'm reporting it anyways as per request.

**Comment by dpaulino** [comment]
starting to think that this is an OS issue. can't seem to reproduce it

**Comment by shef3r** [comment]
It was an OS issue, now it's fixed (at least in stable W11).

![image](https://github.com/jenius-apps/ambie/assets/79228174/6968fdcd-a19c-460f-95cf-7507028ca27c)
