### ISSUE TITLE
If sound is playing, detect close window request and ask user if they're sure

### ISSUE THREAD

**Issue by dpaulino** [jenius-apps/ambie#373]
I accidentally closed my ambie window while I had a sound playing. This led to a jarring experience since I didn't actually want my sound to end. 

It might be helpful to catch this scenario in the future and double check with the user if they really wanted to close. We should also have an option for the user to always close without asking.

**Comment by Pdawg-bytes** [comment]
I can work on this on Monday or Tuesday at the earliest. Sounds like a good improvement to me.
