### ISSUE TITLE
The sound player state remains true when no sounds are playing.

### ISSUE THREAD

**Issue by Pdawg-bytes** [jenius-apps/ambie#381]
Current issue:

When the user removes all sounds from the player, the player `MediaPlaybackState` remains `Playing`, even after all sounds are removed. It is only paused when the user deliberately presses the pause button.

**Comment by Pdawg-bytes** [comment]
@dpaulino for some reason, I can't seem to repro anymore. Today I was testing in both dev and prod and the bug wasn't happening. The expected behavior was executed and the player was paused when all sounds were cleared.

**Comment by dpaulino** [comment]
Fixed with this https://github.com/jenius-apps/ambie/commit/19ef0536fc7406803f51bb418f1427b72da1b29d
