### ISSUE TITLE
Add option to launch automatically on startup

### ISSUE THREAD

**Issue by dpaulino** [jenius-apps/ambie#388]
https://learn.microsoft.com/en-us/uwp/api/windows.applicationmodel.startuptask?view=winrt-22621

**Comment by dpaulino** [comment]
This scenario is surprisingly difficult. Here's the current status
- I have implemented the startup task API as linked above
- Ambie correctly starts on PC startup
- But the API only launches the app in minimized mode (aka the app is not in the foreground)
- This is a problem because the `Background media playback` capability that UWP provides only works when the sound is _started_ in the foreground and then the app goes to the background
- The capability doesn't work when you try to start the sound while the app is already in the background (aka minimized)

The result is:
- The current implementation means that ambie does launch in the taskbar, but sounds aren't playing
- This makes the current implementation worthless since the whole point is to get sounds to start playing right away

**Comment by dpaulino** [comment]
Documentation I found online saying that the capability only works when the sound is started in the foreground: https://social.msdn.microsoft.com/Forums/windows/en-US/f6ecb11e-dbfd-406c-9ffd-5e4c047d3720/background-mediaplayer-not-working-in-uwp-when-minimized?forum=wpdevelop 

![image](https://github.com/jenius-apps/ambie/assets/7649589/943fb7ce-0a40-495c-a2ec-b083cf06a442)

**Comment by dpaulino** [comment]
Proposed alternative solution:
- User signs into PC
- Toast notification launches inviting user to resume Ambie sounds
- User clicks "resume" on toast or clicks on the entire toast in general
- Ambie launches and sounds start playing

**Comment by 4evermaat** [comment]
I disagree that this should be closed.  Users should be offered a CMD option or some command line switches to ensure app loads in the foreground.  And then after starting app, the app is minimized.    

Or you can add a "launcher" type of exe that handles this scenario.
