### ISSUE TITLE
Feature Request: Set Window Title to Track Name

### ISSUE THREAD

**Issue by Saijin-Naib** [jenius-apps/ambie#40]
Not sure if UWP allows this (I have to assume it does), but it'd be nice to see ambie prepend the audio track name to the window name.

So, beach - ambie or such.

**Comment by dpaulino** [comment]
By window title, do you mean here?
![image](https://user-images.githubusercontent.com/7649589/98968888-24d39200-24c3-11eb-9f89-c187db079512.png)

**Comment by Saijin-Naib** [comment]
Like in the attached image
![image](https://user-images.githubusercontent.com/19295950/98969737-27db7c00-24dd-11eb-9755-ee5f6b595661.png)

**Comment by dpaulino** [comment]
ok yup, this is doable. Thanks for the screenshot!

**Comment by Saijin-Naib** [comment]
> 
> 
> ok yup, this is doable. Thanks for the screenshot!

Glad to know. Still miffed Groove doesn't do this, nor use the Taskbar Progress indicator for track progress. Rage!

**Comment by dpaulino** [comment]
Now that Ambie is designed to play multiple sounds simultaneously, I don't think this request makes sense anymore. Closing for now, but feel free to reopen if you can think of a design that makes sense when 3 tracks are playing.

**Comment by Saijin-Naib** [comment]
If you can save those multi-tracks as presets, that preset name could work.
