### ISSUE TITLE
loudest volume problem

### ISSUE THREAD

**Issue by gherbetto** [jenius-apps/ambie#407]
Hello, great app you got here, there is an issue i noticed though. Whenever i launch an app no matter what volume of the sliders was set previously e.g. 20% or 100% the volume of the initial sound when you hit play is insanely LOUD. like 1000%.

Temporary fix for it is:
I have to move all of the sliders at least once for example if it was at 100% i move it 1% lower and the volume becomes normal even at 100% not comparable to what it sounded at the launch of the app.

Let me know if i can help by providing you with more information or to demonstrate it.

**Comment by dpaulino** [comment]
I think I found the problem. Deploying a fix asap

**Comment by gherbetto** [comment]
Oh thank you! I just finished recording just in case.On Dec 8, 2023, at 13:21, Daniel ***@***.***> wrote:﻿
I think I found the problem. Deploying a fix asap

**Comment by gherbetto** [comment]
Oh thank you! I just finished recording just in case. 🙏

**Comment by dpaulino** [comment]
I believe the issue is fixed. Can you try updating to 4.0.21 and let me know?

**Comment by gherbetto** [comment]
Thank you. Sounds great!
But I'm unable to locate that version. In releases there is only 4.0.19

**Comment by dpaulino** [comment]
ah, sorry about that. Try this: https://github.com/jenius-apps/ambie/releases/tag/v4.0.21

**Comment by dpaulino** [comment]
Closing for now. I'll reopen if the issue is still there.

**Comment by gherbetto** [comment]
Wow, you found the solution almost immediately. It's working perfectly now. No more ear abuse) 🙏😊

**Comment by dpaulino** [comment]
Glad to hear, thank you for confirming!
