### ISSUE TITLE
Wallpaper doesn't work

### ISSUE THREAD

**Issue by giseledute** [jenius-apps/ambie#412]
Hello, I've already tried changing the wallpaper to those in the app, I've already put new ones and nothing works, only “light” and “dark” remain, otherwise the wallpaper has no function.

![image](https://github.com/jenius-apps/ambie/assets/110442972/f6276bcb-6465-4429-8788-a9633bce5217)

_My system:
AMD Ryzen 3 2200G Processor with Radeon Vega Graphics 3.50 GHz
Installed RAM 24.0 GB 
System type 64-bit operating system, x64-based processor_

Thank you in advance

**Comment by dpaulino** [comment]
Do you have transparency/animation effects turned on in your Windows OS?

**Comment by giseledute** [comment]
I turned it on and now it works. Thanks!
