### ISSUE TITLE
Streak!

### ISSUE THREAD

**Issue by stilllife94** [jenius-apps/ambie#413]
I have a suggestion: have a “my streak” page where we see the days we worked using ambie.
Example:
![image](https://github.com/jenius-apps/ambie/assets/153905570/44e02efb-48b3-4432-9046-d6d139cc6257)

I think it's a great addition.

**Comment by dpaulino** [comment]
Very cool idea, thanks :)

**Comment by dpaulino** [comment]
Streaks feature will be included in an upcoming build 4.2 or higher :) https://github.com/jenius-apps/ambie/commit/725ec0b01f6e514f277f4ea2c4651fe140358914
