### ISSUE TITLE
Add max width to settings

### ISSUE THREAD

**Issue by itsWindows11** [jenius-apps/ambie#414]
![image](https://github.com/jenius-apps/ambie/assets/81253203/12538910-e290-45fc-83f1-48f4cda61b0a)

In the example screenshot above, there's no sufficient horizontal padding in the settings, which is kind of incoherent with the rest of the inbox UWP apps. The screen also doesn't have max width, which for wide screens may not be usable easily.

**Comment by dpaulino** [comment]
Fixed with https://github.com/jenius-apps/ambie/commit/062e12bb5345e49844b8a11640fd839623b45661
