### ISSUE TITLE
docs/catalogueDocs.md - is this doc relevant or required? 

### ISSUE THREAD

**Issue by aiwilliamson** [jenius-apps/ambie#416]
Hi there! I've been looking around the codebase, and noticed the document at: `docs/catalogueDocs.md`, detailing how to "Upload Sounds to the Ambie Catalogue". 
Though (with this doc last updated March 2021) it doesn't look like the content is accurate or relevant to the current Ambie: the instructions do not correlate to the app itself, and there doesn't appear to be a way to upload a new sound in the app regardless.

**Comment by dpaulino** [comment]
Sorry about that. Uploading sounds to ambie's catalogue has been removed after a pilot experiment showed no success. 

I'll update the docs to remove mentions of uploading sounds.

**Comment by dpaulino** [comment]
Removed outdated docs
