### ISSUE TITLE
Audio stop+restarting when adding sounds

### ISSUE THREAD

**Issue by aiwilliamson** [jenius-apps/ambie#419]
Hey! 

Not sure if this is known or intentional. But I've had an annoyance since the update of slowly fading in / out the ambient sound when pausing & restarting; when adding a sound to the mix (already playing), the sound stops and restarts which may take about half a second. Slightly disturbs the ambiance for me. 

Thanks:)

**Comment by dpaulino** [comment]
I'll take a look thanks

**Comment by dpaulino** [comment]
Apologies for the delay. Fixed here: https://github.com/jenius-apps/ambie/commit/1d6d3270a20766fe96d34c72b17cd815760ac613

**Comment by dpaulino** [comment]
@aiwilliamson @hunterlan the fix is in v4.3.2 and it's now available in the microsoft store :)
