### ISSUE TITLE
When user has Plus, the "Buy Ambie+" link is still showing when the app is offline.

### ISSUE THREAD

**Issue by shef3r** [jenius-apps/ambie#420]
I have Ambie+. When I'm online as I'm launching the app, it's all fine, but when I'm offline, the link shows. No other functionality is affected (I can still play Plus sounds)

**Comment by dpaulino** [comment]
Should be fixed with https://github.com/jenius-apps/ambie/commit/5f36c016ee12601152062fda42531c3038be33e6
