### ISSUE TITLE
Certain sounds aren't working

### ISSUE THREAD

**Issue by haridev-c** [jenius-apps/ambie#425]
https://github.com/jenius-apps/ambie/assets/152641387/4e68220a-c6d8-4be9-82c3-ed27a930c493

Certain sounds downloaded from the catalogue doesn't work

**Comment by dpaulino** [comment]
I'm not able to reproduce on my machines. Can you try reinstalling ambie, downloading one sound, and then letting it play?

**Comment by haridev-c** [comment]
Uploading Ambie2Short - Made with Clipchamp (1).mp4…

I've tried reinstalling twice. The issue's still there on my device.

**Comment by haridev-c** [comment]
https://github.com/jenius-apps/ambie/assets/152641387/d7f7c6e6-175b-4425-925a-fef9f2e690e9

I've tried reinstalling the app twice. The issue's still there on my device. 

(I've sped up the video to compensate for slow download speed)

**Comment by dpaulino** [comment]
Hmm, this is strange. Can you share more information about your device? 
- OS version
- device model 
- How many hard drives do you have on the machin? E.g. C:\, D:\ = 2 drives
- And which drive did you install ambie in?

**Comment by haridev-c** [comment]
- OS Version: version 23H2 (0S Build 22631.3007)
- Device Model: Acer Nitro 5 (AN515-44)
- No. of Hard drives: 3 
- Ambie is installed in C drive

**Comment by Raynbda** [comment]
I have this issue too. on sounds like turning pages, library, cicadas and more

**Comment by Raynbda** [comment]
update: uninstalling and installing ambie again fixed the issue
