### ISSUE TITLE
Skip rest segment button does not clear the next toast notification

### ISSUE THREAD

**Issue by dpaulino** [jenius-apps/ambie#426]
Repro:
- Rest segment starts
- Click skip rest segment
- Observe the "time to focus" notification still appears even though we're already focusing.

**Comment by shef3r** [comment]
It would be a bit hacky, but wouldn't it be possible to pause the toast service for a couple seconds so that the notification doesn't send?

**Comment by dpaulino** [comment]
Fixed in v4.3
