### ISSUE TITLE
Some corners get cut off when they are animated on hover

### ISSUE THREAD

**Issue by BreeceW** [jenius-apps/ambie#43]
![Ambie logo cut off on right and bottom](https://user-images.githubusercontent.com/18747724/98765104-51948600-23ab-11eb-9ad8-5868b740ad0d.png)
![Sound on left cut off on left](https://user-images.githubusercontent.com/18747724/98765131-61ac6580-23ab-11eb-9924-185a5f52024e.png)
These are a couple instances where the UI gets cut off in Ambie.
I know animations are a key part of the app, and this messes with that goal a bit.
The Ambie icon is also pretty off-center (more pronounced at high DPI scaling).

**Comment by dpaulino** [comment]
Are you still seeing this in master branch? I believe I fixed the image being cut off. But the logo issue may still be there

**Comment by dpaulino** [comment]
I think this is fixed in 0.8.9.
