### ISSUE TITLE
[Feature Request] Add an option to disable windows media controls

### ISSUE THREAD

**Issue by djsleahy** [jenius-apps/ambie#438]
The app is very effective at drowing out background noise using white noise.

However, I oftentimes I'll be playing a piece of media (eg. video on topic of study), and will use the windows media controls to play/pause that video (aka. keyboard media controls). Unfortunately, sometimes Ambie will take focus from the targetted application (web browser or media player) and the media controls will instead play/pause the white noise.

Adding the option to disbale media controls for the Ambie application would help with this.

**Comment by dpaulino** [comment]
I've tried this before, unfortunately, and it leads to big bugs in the playback of Ambie so I had to remove it. 

At the end of the day, the core issue is in the Windows. They need to provide a better experience when managing sounds from multiple apps. The current UI has that tiny little arrow that you have to click to switch the media controls to another app. It's not an intuitive or easy-to-use system. 

I recommend sending a feedback hub report to Windows using Win+F.
