### ISSUE TITLE
Track end time is not displayed correctly

### ISSUE THREAD

**Issue by TIMBLOCKER** [jenius-apps/ambie#450]
When there is an active focus track, the end time of said track is "increasing". 
This happens every time the popout is maximized in the session and it seems that the end time is recalculated then.

This is a problem because if you happen to turn on the ambie window i.e. during the break of your session, the time is recalculated and you have no option of seeing your tacks end time. The newly calculated time seems to be the end time, if I were to start the entire track over from now. (I started 10:14 with 40min solts and 8min breaks)

![image](https://github.com/user-attachments/assets/d0232eff-e9c2-48ff-90e5-23926d00655a)

In any case: Thanks for publishing this amazing app. It's getting me through some hard learning crunch right now ;)

Greetings from Germany
Tim

**Comment by dpaulino** [comment]
Oh no, thanks for spotting this and sharing. I'll fix it as soon as possible!

**Comment by dpaulino** [comment]
Issues has been fixed. It will be available in the next update. I will post back here when the update is available

**Comment by dpaulino** [comment]
Fix has been released in Ambie 4.5.7. If you don't have the new update yet, here's how to get it: open the Microsoft Store app > go to the Downloads page > click Get Updates
