### ISSUE TITLE
Blank Screen on startup

### ISSUE THREAD

**Issue by kameshkotwani** [jenius-apps/ambie#47]
After updating to 0.8.7.0, a simple black screen opens up. 
I have tried restarting the app several times.
![ApplicationFrameHost_k7C8HRdYE2](https://user-images.githubusercontent.com/36355951/98893163-e8566500-24c7-11eb-80f3-322516c2e6a8.jpg)

**Comment by dpaulino** [comment]
Thanks for reporting. I actually deployed a new update already. v0.8.8 restores the app back to normal

**Comment by dpaulino** [comment]
try getting v0.8.8 and let me know if you're still getting an issue

**Comment by dpaulino** [comment]
![image](https://user-images.githubusercontent.com/7649589/98893962-87dc0f00-2458-11eb-84fa-70ff7de96f15.png)

**Comment by dpaulino** [comment]
This commit fixes the root cause of this issue. 
https://github.com/jenius-apps/ambie/commit/09247172c47aa690dc0ce7a72e3f3f424bb4238e
