### ISSUE TITLE
Feature Request: Use Taskbar Progress Indicator

### ISSUE THREAD

**Issue by Saijin-Naib** [jenius-apps/ambie#50]
I'd like to see the Taskbar Progress Indicator be used to show how far within a loop the playback is currently.

**Comment by dpaulino** [comment]
Out of curiosity, what's the scenario for knowing the position of the current track? Are you wanting to move to a next track once the a loop is done? I'm wondering because there may be other feature we can build to achieve your end goal

**Comment by Saijin-Naib** [comment]
More a weird compulsion to know, and I like how it looks aesthetically

**Comment by dpaulino** [comment]
Looks like this functionality isn't available for modern Windows apps https://github.com/microsoft/ProjectReunion/issues/68#. So I will close this for now. We can revisit if/when the feature is available.
