### ISSUE TITLE
[A11y] Sound loading progress ring can be reached using narrator, even if all sounds have been loaded

### ISSUE THREAD

**Issue by chingucoding** [jenius-apps/ambie#54]
When using the item mode of narrator, users can reach the "loading sound" progressring despite all sounds having been loaded.

**Comment by dpaulino** [comment]
Can you provide repro steps? What is item mode? Sorry I'm still learning my way around a11y!

**Comment by chingucoding** [comment]
I was navigating in item mode, after going through the different sounds, eventually you reach the ProgressRing.
