### ISSUE TITLE
Feature : Animation with sound

### ISSUE THREAD

**Issue by harun** [jenius-apps/ambie#6]
Is it possible to add animation for the sounds with full screen ?

ie, fireplace with fireplace animation like https://www.youtube.com/watch?v=L_LUpnjgPso

**Comment by smmatte** [comment]
+1 would be great for Xbox

**Comment by dpaulino** [comment]
@harun A screensaver was added in one of the recent updates. Have you given it a try? If so, does it suffice? Or a video-based screensaver would still be preferred?

**Comment by michael-hawker** [comment]
Reminded me of the sound visualizer plugins for Winamp... 🙂

**Comment by validvoid** [comment]
How about a shader-based visualizer?
