### ISSUE TITLE
EXE or MSI

### ISSUE THREAD

**Issue by thevitormanuel** [jenius-apps/ambie#69]
Hi, 

Please create a .EXE or .MSI file, I can't use Windows Store (I use Windows 10 Enterprise N). 

Thanks a lot in advance.

**Comment by dpaulino** [comment]
Here's an installer. You don't need the windows store for this installer. https://github.com/jenius-apps/ambie/releases/tag/v0.8.9

**Comment by thevitormanuel** [comment]
I try this file but I can't open or installer...

I used the LTSC Windows version... Windows can't open this file... 

![image](https://user-images.githubusercontent.com/56034808/100261831-9f80c080-2f4b-11eb-8420-e87e3926e511.png)


Best regards.

**Comment by dpaulino** [comment]
Ah shoot. Do you have this app installed on your machine? https://www.microsoft.com/store/productId/9NBLGGH4NNS1. If you don't have this, maybe you can ask your IT department to add it. This app is just an installer (like MSI installer)

**Comment by thevitormanuel** [comment]
Thanks a lot for the information!!!
