### ISSUE TITLE
[Featue] UI tweaks

### ISSUE THREAD

**Issue by KristofKekesi** [jenius-apps/ambie#7]
## UI Changes
I like the UI very much, but when I resise the window the buttons should be centered.
If there would be a setting to make the top bar acrylic that would be cool.

By the way it is very useful. 👍

**Comment by dpaulino** [comment]
Thanks for reaching out! Regarding the top bar, it is acrylic 😜

**Comment by Jaiganeshkumaran** [comment]
@dpaulino Where's acrylic in this? I just see a grey background
![திரைப்பிடிப்பு (102)](https://user-images.githubusercontent.com/45227503/98522763-17d45a00-229b-11eb-95a5-aa076e580d9a.png)

**Comment by KristofKekesi** [comment]
When you scroll down (in a smaller window).

**Comment by Jaiganeshkumaran** [comment]
@KristofKekesi On a larger screen, why not make the bar acrylic the desktop background and on small disable it and show the scrolled position?

**Comment by KristofKekesi** [comment]
That was I asking for.

**Comment by dpaulino** [comment]
The top bar is in-app acrylic (instead of host background acrylic) by design, so I won't make changes there. But grid is now centered. Coming in the next update 🙂
![image](https://user-images.githubusercontent.com/7649589/99204028-3047e700-2769-11eb-92fb-eece71377c70.png)

**Comment by KristofKekesi** [comment]
Thanks!
