### ISSUE TITLE
Weird/messed up czech translation.

### ISSUE THREAD

**Issue by muznyo** [jenius-apps/ambie#70]
I checked the whole app and there was a messed up translation in settings (the radiobutton part).
![image](https://user-images.githubusercontent.com/24987471/100277954-55f09f80-2f64-11eb-996c-b4ee5ec61bb4.png)

**Comment by KristofKekesi** [comment]
Oh thats hungarian.
Btw when I translatted the hungarian xml I saw there some weird words. That must have been czech.

**Comment by muznyo** [comment]
probably

**Comment by dpaulino** [comment]
Fixed by @MichalMoudry. Thank you!
