### ISSUE TITLE
Feature request: reminders

### ISSUE THREAD

**Issue by dpaulino** [jenius-apps/ambie#98]

**Comment by michael-hawker** [comment]
? Would this be to notify you when something's happening. Wouldn't that just be something you could do in the Alarms app?

**Comment by dpaulino** [comment]
The idea came from a friend who said they wanted to be reminded to use ambie at the end of their work day. Yes they could just set a reminder using To Do or their calendar, but they were wanting a more integrated experience. Basically they want this UX: reminder pop up > click reminder > ambie opens and automatically starts playing.

**Comment by dpaulino** [comment]
Closing this because there will be other ways for ambie to remind people to play sounds.
