### ISSUE TITLE
[A11y] Sleep timer button name is too descriptive

### ISSUE THREAD

**Issue by chingucoding** [jenius-apps/ambie#99]
The sleep timer button has the UIA name "Click here to set up a sleep timer, where the sound will pause after the selected time." While this is fine as a tooltip, this should not be the UIA name as it is to much information. Putting this in the help information of the button and naming it "Sleep time" or similar would be a better option in my opinion.

**Comment by dpaulino** [comment]
Addressed in https://github.com/jenius-apps/ambie/commit/410208dbf1be00b1999eb92bb93bb9f0540c21d4
